В этой практической работе три обязательные задачи и одна дополнительная.

*Обязательные задачи* нужно сделать для того, чтобы проверить, что вы действительно усвоили материал модуля. Сдайте их на проверку.

*Дополнительная задача* для тех, кто чувствует, что нужно ещё немного потренироваться в подборе правильных критериев для проверки гипотез. Вы также можете сдать её на проверку и получить обратную связь.

Удачи!

## Цели практической работы

Проверить:
*   постановку нулевых и альтернативных гипотез,
*   выбор статистического критерия для проверки гипотез,
*   умение пользоваться Т-критериями,
*   умение пользоваться непараметрическими критериями.

Потренироваться в постановке односторонних и двусторонних тестов.

## Что оценивается

*   Все условия для применения критерия проверены.
*   Применение того или иного критерия обосновано текстом.
*   В каждой задаче присутствует текстовое объяснение почему нулевая гипотеза не может быть отвергнута.

## Как отправить работу на проверку
Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему куратору.

##Обязательные задачи

*Задача 1*

Студентов с одним и тем же начальным уровнем английского языка поделили на две группы. Одну группу учили по методике X, а другую по методике Y. После прохождения обучения им дали одинаковые финальные тесты на знание языка. За тест можно получить от 0 до 100 баллов. Проверьте, являются ли статистически значимыми различия в оценках между группой, которая училась по методике X, и группой, которая училась по методике Y.
______________
Опишите словами нулевую и альтернативную гипотезы. Проверьте гипотезы с помощью статистического критерия. Интерпретируйте получившиеся результаты. Уровень значимости = 5%.

In [ ]:
#Нулевая гипотеза:Средние баллы в группах X и Y одинаковые.

#Альтернативная гипотеза: Средние баллы в группах X и Y различаются.

In [ ]:
# строка для тех, кто работает в colab
!pip install scipy==1.7.1

Collecting scipy==1.7.1
  Downloading scipy-1.7.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (28.5 MB)
     |████████████████████████████████| 28.5 MB 29.2 MB/s
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in /usr/local/lib/python3.7/dist-packages (from scipy==1.7.1) (1.21.5)
Installing collected packages: scipy
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed scipy-1.7.1

In [5]:
import pandas as pd
from scipy import stats

df = pd.read_csv('data/hw1.csv')
df.head()

    X   Y
0  57  64
1  67  67
2  58  62
3  55  59
4  54  65

In [21]:
# Ваш код здесь
stats.shapiro(df.X)

ShapiroResult(statistic=0.984373122264943, pvalue=0.2859461687571367)

In [19]:
stats.shapiro(df.Y)

ShapiroResult(statistic=0.9864255697754221, pvalue=0.40016888333565676)

In [23]:
stats.levene(df.X, df.Y)

LeveneResult(statistic=21.696306698497402, pvalue=5.850812069599258e-06)

In [25]:
stats.ttest_ind(df.X, df.Y, equal_var=False)

TtestResult(statistic=-0.6292883911384963, pvalue=0.5300187896437802, df=167.2694203798624)

In [ ]:
#На уровне значимости 5% не обнаружено статистически значимых различий между средними баллами студентов, обучавшихся по методикам X и Y.
#Методики X и Y дали схожие результаты по финальному тесту.

*Задача 2*

Ученые придумали добавку для уменьшения веса за две недели. Для проведения эксперимента и проверки добавки набрали тестовую группу из 60 человек. Было произведено два замера веса: один до приема добавок, другой после двухнедельного курса. Изучите данные и сделайте вывод, значимо или незначимо уменьшился вес у тестовой группы.

______________
Опишите словами нулевую и альтернативную гипотезы. Проверьте гипотезы с помощью статистического критерия. Интерпретируйте получившиеся результаты. Уровень значимости = 5%.

Нулевая гипотеза:Средний вес не изменился после приёма добавки.

Альтернативная гипотеза: Средний вес уменьшился после приёма добавки.

In [29]:
df2 = pd.read_csv('data/hw2.csv')
df2.head()

   before  after
0      66     68
1      68     68
2      59     60
3      64     62
4      75     71

In [35]:
# Ваш код здесь
df2['diff'] = df2['before'] - df2['after']
df2.head()

   before  after  diff
0      66     68    -2
1      68     68     0
2      59     60    -1
3      64     62     2
4      75     71     4

In [37]:
stats.shapiro(df2.diff)

ShapiroResult(statistic=0.9114998888020539, pvalue=0.00035477016914973157)

In [39]:
stats.wilcoxon(df2.before, df2.after, alternative='greater')

WilcoxonResult(statistic=891.0, pvalue=0.015451189209392365)

In [ ]:
#Средний вес уменьшился после приёма добавки.

*Задача 3*

Вы работаете аналитиком в приложении, которое собирает новости по интересам пользователя. Например, если пользователь увлечен книгами,  то приложение будет собирать ему самые свежие новости по новым книгам. Вы заметили, что пользователи редко посещают ваше приложение, а вам хотелось бы поднять их активность и видеть, что они заходят в приложение каждый день или еще чаще. То есть поднять их заинтересованность. 

Вы и группа разработки решили присылать уведомления раз в день с самой популярной новостью по тематикам пользователя. Теперь вам нужно проверить, что эта гипотеза сработала, и заинтересованность пользователя выросла.
______________________
В датасете для каждого пользователя указано, сколько раз в неделю он заходил до появления уведомлений (колонка `before`) и сколько раз в неделю он стал заходить в приложение после появления уведомлений (колонка `after`)
______________
Опишите словами нулевую и альтернативную гипотезы. Проверьте гипотезы с помощью статистического критерия. Интерпретируйте получившиеся результаты. Уровень значимости = 5%.

Нулевая гипотеза:частота заходов в приложение не изменилась после введения уведомлений.

Альтернативная гипотеза: частота заходов увеличилась после введения уведомлений.

In [41]:
df3 = pd.read_csv('data/hw3.csv')
df3.head()

   id  before  after
0  15       3     11
1   7       6     13
2   6       3      8
3  13       1     14
4  11       3      4

In [53]:
# Ваш код здесь
df3['diff'] = df3['before'] - df3['after']
df3.head()

   id  before  after  diff
0  15       3     11    -8
1   7       6     13    -7
2   6       3      8    -5
3  13       1     14   -13
4  11       3      4    -1

In [55]:
stats.shapiro(df3['diff'])

ShapiroResult(statistic=0.9623316737992681, pvalue=0.11132400864196375)

In [63]:
stats.ttest_rel(df3.after, df3.before, alternative='greater')

TtestResult(statistic=5.193709231561377, pvalue=1.9840383037602486e-06, df=49)

In [ ]:
#активность выросла

## Дополнительная задача

*Задача 4*

Компания X тестирует продажу своего продукта через два разных сайта. На оба сайта приходит одинаковое количество пользователей. Причем выборки пользователей не пересекаются, то есть если пользователь увидел сайт 1, он уже не посетит сайт 2. Проверьте гипотезу, что средний чек по пользователям на сайте 1 отличается от среднего чека пользователей на сайте 2 (период сравнения — один месяц).

Опишите словами нулевую и альтернативную гипотезы. Проверьте гипотезы с помощью статистического критерия. Интерпретируйте получившиеся результаты. Уровень значимости = 5%.

Нулевая гипотеза:средний чек пользователей на сайте 1 равен среднему чеку пользователей на сайте 2.

Альтернативная гипотеза: средний чек пользователей на сайте 1 отличается от среднего чека пользователей на сайте 2.

In [65]:
df4 = pd.read_csv('data/hw4.csv')
df4.head()

   site1  site2
0    193    720
1   8426   2099
2   4024   2282
3   1447   2455
4   2274   7988

In [67]:
# Ваш код здесь
stats.shapiro(df4.site1)

ShapiroResult(statistic=0.8995057589416227, pvalue=1.340241032328672e-06)

In [69]:
stats.shapiro(df4.site2)

ShapiroResult(statistic=0.9372696707235851, pvalue=0.00013189940318116873)

In [73]:
stats.mannwhitneyu(df4.site1, df4.site2, alternative='two-sided')

MannwhitneyuResult(statistic=3889.5, pvalue=0.00666469719769119)

In [75]:
#средний чек пользователей на сайте 1 отличается от среднего чека пользователей на сайте 2.